<p class="alert alert-info">
	<strong>Donate via PayPal or Bitcoin if you want to. The money goes into getting a new hoster.
	<span class="donate-btns">
		<a class="donate-btn donate-paypal" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GWAFLGBJ9CFYC" target="_BLANK">
			<span class="icon icon-paypal"></span>
			PayPal
		</a>
		<a class="donate-btn donate-bitcoin">
			<span class="icon icon-bitcoin"></span>3NxDrGypxkvuLnsn6s6Taf9DNDV44199KA
		</a>
	</span>
</p>