{% extends "layout.swig" %}

{% block title %}obligatory infopage{% endblock %}
{% block body %}
<div class="jumbotron">
<h1>404</h1>
</div>
There's nothing to be found right here.
Reasons for this could be
<ul>
	<li>Your file was deleted due to abuse or other rule violations</li>
	<li>The link you got is wrong</li>
</ul>
<p>Questions? Go to <a href="http://1339.cf/faq.html">our info page</a> or back to <a href="http://1339.cf/">1339.cf</a></p>
</ul>
{% endblock %}