{% extends "layout.swig" %}

{% block title %}1339.CF Tools{% endblock %}
{% block body %}
<div class="jumbotron">
<h1>Tools</h1>
</div>
<section><h1>limf</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://github.com/Lichinlich/limf">https://github.com/Lichinlich/limf</a></dd>
	<dt>Contact</dt>
		<dd><a href="http://lich.neocities.org/">http://lich.neocities.org/</a></dd>
</dl></section>
<p><a href="http://1339.cf/">back to 1339.cf</a>
</p>
{% endblock %}
