{% extends "layout.swig" %}

{% block title %}1339.CF Tools{% endblock %}
{% block body %}
<div class="jumbotron">
<h1>Tools</h1>
</div>
<section><h1>ShareX</h1><dl>
	<dt>Download</dt>
		<dd><a href="/1339sharex.json">http://1339.cf/1339sharex.json</a></dd>
</dl></section>
<section><h1>limf</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://github.com/lich/limf">https://github.com/lich/limf</a></dd>
	<dt>Contact</dt>
		<dd><a href="http://lich.github.io/">http://lich.github.io//</a></dd>
</dl></section>
<section><h1>1339secure</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://github.com/AdrianKoshka/1339secure">https://github.com/AdrianKoshka/1339secure</a></dd>
	<dt>Contact</dt>
		<dd><a href="mailto:adriankoshcha@teknik.io">adriankoshcha@teknik.io</a></dd>
</dl></section>
<section><h1>gyazowin</h1><dl>
	<dt>Download</dt>
		<dd><a href="http://getrektby.us/dl/1339.zip">http://getrektby.us/dl/1339.zip</a></dd>
		<dt>Source</dt>
		<dd><a href="https://github.com/avail/gyazowin">https://github.com/avail/gyazowin</a></dd>
	<dt>Contact</dt>
		<dd><a href="mailto:avail@pomf.se">avail@pomf.se</a></dd>
</dl></section>
<p><a href="/">back to 1339.cf</a>
</p>
{% endblock %}
